### PR TITLE
feat(smoke): scaffold S3 full-stack happy-path smoke harness (Task #2)

### PR DESCRIPTION
**Pull request by Jiahui-Gu**
## Summary

Adds `packages/smoke/` — a local-only Playwright harness that orchestrates the cloud-mode S3 stack (Tauri shell spawning daemon + wrangler dev cf-worker + wrangler pages dev frontend-web + Playwright chromium) and runs one happy-path spec.

Per the rewritten Task #2 spec, this PR is **scaffold + red-only**: the smoke harness exists, runs, and produces a real failure trace; closing the gap to green is intentionally **out of scope** and will be picked up as separate followup PRs based on the root-cause list below. **No product `src/` is touched** — this PR adds files only under `packages/smoke/`, plus a one-line root `package.json` smoke script and the lockfile delta.

## Coverage audit (S3 unit invariants)

The Task #2 spec lists 6 unit invariants and asks for them either as new test files or as an audit pointing at existing coverage. After reading the existing test files, all 6 are already covered by S3 main-line PRs (#1166-#1174). No new unit tests added; pointers below for reviewer convenience.

| spec invariant | covered by | file:line |
|---|---|---|
| (a) `tunnel-do-hello-sid`: ws_open(sid=X) → daemon receives hello with same sid (#1174) | `packages/cf-worker/test/tunnel-do.test.ts` | hello sid+lastSeq cases at lines 376-441 (3 cases: sid+lastSeq propagation, default lastSeq=0, missing/empty sid → 1008, invalid lastSeq → 0) |
| (b) `tunnel-do-http-buffer`: http_req before any browser pairing is forwarded to daemon (#1172) | `packages/cf-worker/test/tunnel-do.test.ts` | "proxyHttp succeeds without any browser /ws/default pairing" at lines 569-596 |
| (c) `tunnel-do-hibernation`: DO wake recovers daemon socket via state.getWebSockets; routes still work (#1173) | `packages/cf-worker/test/tunnel-do.test.ts` | "hibernate -> wake: daemon socket is recovered" + "browser token is restored from ws.deserializeAttachment" at lines 600-653 |
| (d) `tunnel-hello-gate`: pre-hello binary / non-control text rejected with close 1008 | `packages/daemon/test/tunnel.test.ts` | binary-before-hello (155-171), malformed (173-186), bad-token (136-153), and post-#1172 invariants (576-607) |
| (e) `tunnel-http-req-resp`: http_req routed to fetch loopback, http_res replied with same id (#1170) | `packages/daemon/test/tunnel.test.ts` | "handles inbound http_req: fetches loopback and replies http_res" + http_req body / 502 / not-forwarded-to-onFrame cases at lines 336-491 |
| (f) `resolveToken-cloud`: cross-origin token bootstrap uses absolute `<daemonBase>/token` URL, not relative | `packages/frontend-web/test/resolveToken.test.ts` | "cross-origin (daemonBase set)" describe block at lines 79-185 (7 cases) |

Coverage is OK without new unit files. If reviewer prefers physical file separation per spec list, can split in a followup — semantics already pass.

## Phase 1: red

`pnpm --filter @ccsm/smoke run smoke` on Windows host. cf-worker (wrangler dev) starts cleanly; pages-dev (wrangler pages dev) immediately exits with code 1; tauri-dev never gets a chance to spawn:

```
> @ccsm/smoke@0.0.0 smoke C:\Users\jiahuigu\ccsm-worktrees\pool-3\packages\smoke
> playwright test

[cf-worker] Starting local server...
[cf-worker] [wrangler:inf] Ready on http://127.0.0.1:8787
[cf-worker] [wrangler-UserWorker:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2025-07-18",
but you've requested "2026-01-01". Falling back to "2025-07-18"...
[pages-dev] [ERROR] Specify either a directory OR a proxy command, not both.
[pages-dev] Logs were written to "...\wrangler-2026-05-08_10-42-35_711.log"
Error: [pages-dev] exited before ready (code=1, signal=null)
   at ..\fixtures\orchestrator.ts:102

  100 |     child.on('exit', (code, signal) => {
  101 |       clearTimeout(t);
> 102 |       rejectReady(new Error(
      |                   ^
  103 |         `[${opts.name}] exited before ready (code=${code}, signal=${signal})`,
  104 |       ));
  105 |     });
```

This is the "现在不通的" signal: with S3 main-line product (#1166-#1174) merged, the cloud-mode loop is conceptually wired but operationally not runnable end-to-end on a local box. The orchestrator fails fast at the first missing piece (#R-1 below); the rest are discovered by static reading of product source.

## Red root causes

Each entry: `[package] root cause` — `file:line` where the gap lives + scope of fix needed. **No fix is attempted in this PR** (per task spec; per dev rule "跨 5 层 bug 一锅炖" red line). Manager picks these up as separate followups.

- **#R-1 — observed at runtime, blocking** — `[smoke]` `wrangler pages dev --port N -- pnpm dev` rejected with "Specify either a directory OR a proxy command, not both". `packages/smoke/fixtures/orchestrator.ts:135-148`. wrangler 3.x requires either positional directory OR `--` proxy command, not both. **Scope**: smoke-only. Two viable paths: (i) `pnpm --filter @ccsm/frontend-web build` first, then `wrangler pages dev dist/`, or (ii) drop wrangler pages dev for vite + a small middleware that mounts `[[path]].ts` as Express handlers. Option (i) is closer to prod parity.

- **#R-2 — would surface after #R-1 fixed** — `[frontend-web]` Pages Function `[[path]].ts` is hard-wired to the production `wss://cc-sm.pages.dev` worker origin; under `wrangler pages dev` against a local cf-worker the proxy points at the wrong host. `packages/frontend-web/functions/[[path]].ts` (entire file). **Scope**: frontend-web Function + cf-worker wrangler config. Add a `WORKER_ORIGIN` env binding the Function reads, set via `wrangler pages dev --binding WORKER_ORIGIN=http://127.0.0.1:8787` in the smoke orchestrator. Production binding stays unchanged so prod path is unaffected.

- **#R-3 — would surface after #R-2 fixed** — `[frontend-tauri]` Tauri shell does not propagate `CCSM_TUNNEL_URL` env to the daemon child. `packages/frontend-tauri/src-tauri/src/daemon_mgr.rs:122-153` (`Command::new(node_bin)` only sets `CCSM_DB_PATH`, `CCSM_TOKEN`, `PORT` — no `CCSM_TUNNEL_URL`). With this gap the daemon hard-defaults to `wss://cc-sm.pages.dev/tunnel/default` (`packages/daemon/src/index.mts:34, 134`) and dials prod even when our local wrangler dev worker is up. **Scope**: Rust-only, ~3 lines: read `std::env::var("CCSM_TUNNEL_URL")`, set on the `Command` env. Does not affect prod default behavior.

- **#R-4 — would surface after #R-3 fixed** — `[frontend-tauri]` Webview `App.tsx` does not auto-`invoke('start_daemon')` on mount. `packages/frontend-tauri/src/App.tsx`. The Tauri shell launches but sits idle until a user clicks; smoke has no human in the loop. **Scope**: TS-only, gated by a dev/build flag so production retains explicit-gesture UX if that is the desired contract. Alternative: change `tauri.conf.json` to call `start_daemon` from `setup` hook in `lib.rs` instead of via webview invoke (architectural decision, manager calls).

- **#R-5 — would surface after #R-4 fixed** — `[frontend-web]` Token bootstrap path under wrangler pages dev. `packages/frontend-web/src/hostConfig.ts:60-78` (`resolveToken`) falls back to `GET <daemonBase>/token`. In the prod cloud topology the Pages Function injects the token via header/cookie before the SPA boots; under wrangler pages dev that injection does not happen, so the SPA will hit `/token` against the local Pages origin and the Function will need to forward (or inject) it. Existing unit test `packages/frontend-web/test/resolveToken.test.ts:79-185` covers the "absolute URL fetch" branch; what is missing is a runtime-level integration story for "Pages Function injects token before SPA loads". **Scope**: frontend-web Function + likely a smoke-only `?daemon=` override path. Smaller than R-2/R-3/R-4.

- **#R-6 — environmental, easy** — `[smoke]` Playwright browser binaries are not installed in the pool. `packages/smoke/package.json` declares `@playwright/test` but `playwright install chromium` was never run. **Scope**: smoke-only. README + a `postinstall` hook, or document `npx playwright install chromium` as a one-time setup step. Not on the critical path until R-1 through R-5 land.

Order of fix: R-1 → R-2 → R-3 → R-4 → R-5 → R-6 (R-1 is blocking observation; later items are static-read predictions and may shift order once each is unblocked).

## Local checks (host: Windows 11, mode: fast)

- lint: 2 pre-existing warnings on `packages/daemon/test/persist.test.ts` and `packages/ui/test/BootstrapRefresh.test.tsx`, unchanged on `origin/working` — verified by patch-flow baseline reset; not in my scope to fix in this PR
- typecheck: OK for everything I touched (`packages/smoke` typecheck Done; `packages/cf-worker`, `packages/shared` Done). Pre-existing failure in `@ccsm/core` (`Cannot find module '@ccsm/shared'` because shared dist is not built before core typechecks in `pnpm -r run typecheck`) is also unchanged on origin/working — verified by patch-flow baseline reset
- build (shared, prerequisite for tests): `pnpm --filter @ccsm/shared run build` OK
- unit tests on the 3 S3 packages (no smoke):
  ```
  packages/cf-worker test:    Test Files  1 passed (1)    Tests  29 passed (29)
  packages/daemon test:       Test Files 13 passed (13)   Tests 142 passed | 1 skipped (143)
  packages/frontend-web test: Test Files  2 passed (2)    Tests  21 passed (21)
  ```
  All 192 existing unit tests still pass; this PR does not modify any existing test or src under `packages/{cf-worker,daemon,frontend-web}/`
- smoke: red as documented in `## Phase 1: red` above

## Rebased on Task #1

Branched from `origin/working` at `df890374 chore(e2e): drop legacy e2e + e2e-tauri packages, remove e2e CI job (#1175)`. The lockfile diff in this PR includes the post-#1175 e2e/e2e-tauri removals (the pool's `node_modules` previously held an older lockfile snapshot) plus the new `@playwright/test` entry for `@ccsm/smoke`.

## Why Draft

Phase 2 green is explicitly out of scope. Marking ready for review when manager confirms the root-cause list is the right decomposition; followup PRs will turn each `#R-N` from red to green individually.

Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Jiahui-Gu** [comment]
APPROVE (self-review token limit, comment 代替 review)

核验通过 (非常规 review, manager 重定向 scaffold+red-only spec):
1. 0 行 src/functions 改动 ✓
2. PR body 4 段齐 (Phase 1 red 真 stderr / 6 条 root causes / Coverage audit / Local checks) ✓
3. 无 .skip/xit/continue-on-error 引入 ✓
4. daemon lifecycle.test.ts:182 it.skipIf(win32) 是 b2972021 (#1163) 历史遗留 ✓
5. CI 全绿 ✓
6. R-1/R-3/R-5 file:line 抽查命中 (daemon_mgr.rs:124 缺 CCSM_TUNNEL_URL, daemon/src/index.mts:34 DEFAULT_TUNNEL_URL, hostConfig.ts:65 resolveToken)

direction 正确, 6 条 root cause 结构 actionable, manager 可逐条拆 followup。Merging.
